title: Crested Critters
collections:
  products:
    output: true
    permalink: /products/:name/

defaults:
  - scope:
      path: ""
      type: "products"
    values:
      layout: product

      collections:
  products:
    output: true
  guides:
    output: true
    permalink: /care/:slug/

